# Generated by Django 4.0.5 on 2022-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyId', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=300)),
                ('itemPrice', models.CharField(max_length=200)),
                ('totalQty', models.CharField(max_length=20)),
                ('totalPrice', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'buying',
            },
        ),
    ]
