# Generated by Django 4.0.5 on 2022-06-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='totalPrice',
        ),
    ]
